# Generated by Django 5.1.7 on 2025-04-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='preço')),
                ('size', models.IntegerField(default=0, verbose_name='tamanho')),
                ('unit', models.CharField(choices=[('un', 'Unidade(s)'), ('g', 'Grama(s)'), ('kg', 'Quilograma(s)'), ('ml', 'Mililitro(s)'), ('l', 'Litro(s)')], max_length=2, verbose_name='unidade de medida')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='media/items/', verbose_name='imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'itens',
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='preço')),
                ('size', models.IntegerField(default=0, verbose_name='tamanho')),
                ('unit', models.CharField(choices=[('un', 'Unidade(s)'), ('g', 'Grama(s)'), ('kg', 'Quilograma(s)'), ('ml', 'Mililitro(s)'), ('l', 'Litro(s)')], max_length=2, verbose_name='unidade de medida')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='media/products/', verbose_name='imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'db_table': 'product',
            },
        ),
    ]
