# Generated by Django 5.1.7 on 2025-04-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Máximo de 10 dígitos, 2 casas decimais.', max_digits=10, verbose_name='preço')),
                ('size', models.IntegerField(default=0, help_text='Quantidade que vai no item. Ex: 1 un, 180g, 437ml, 1kg...', verbose_name='tamanho')),
                ('unit', models.CharField(choices=[('un', 'Unidade(s)'), ('g', 'Grama(s)'), ('kg', 'Quilograma(s)'), ('ml', 'Mililitro(s)'), ('l', 'Litro(s)')], max_length=2, verbose_name='unidade de medida')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='media/items/', verbose_name='imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'adicional',
                'verbose_name_plural': 'adicionais',
                'db_table': 'additional',
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Máximo de 10 dígitos, 2 casas decimais.', max_digits=10, verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(default=0, help_text='Quantidade que vai no item. Ex: 1 un, 180g, 437ml, 1kg...', verbose_name='tamanho'),
        ),
    ]
