# Generated by Django 5.1.7 on 2025-05-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('product', '0002_additional_delete_item_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalcategory',
            name='product',
        ),
        migrations.AlterField(
            model_name='additionalcategory',
            name='type',
            field=models.CharField(choices=[('choose one', 'Escolher uma opção'), ('select multiple', 'Selecionar várias opções'), ('add on', 'Adicionar mais')], max_length=15, verbose_name='tipo'),
        ),
        migrations.AddField(
            model_name='additionalcategory',
            name='product',
            field=models.ManyToManyField(blank=True, default=None, related_name='additional_categories', to='product.product', verbose_name='produto'),
        ),
    ]
