# Generated by Django 5.1.7 on 2025-05-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_additionalcategory_product_and_more'),
        ('product', '0002_additional_delete_item_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalcategory',
            name='product',
        ),
        migrations.AddField(
            model_name='additionalcategory',
            name='products',
            field=models.ManyToManyField(blank=True, default=None, related_name='additional_categories', to='product.product', verbose_name='produtos'),
        ),
    ]
