# Generated by Django 5.1.7 on 2025-05-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_additionalcategory_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalcategory',
            name='order',
            field=models.IntegerField(default=0, verbose_name='ordem'),
        ),
    ]
