# Generated by Django 5.1.7 on 2025-04-14 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_additional_delete_item_alter_product_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='número do pedido')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('preparing', 'Preparando'), ('delivering', 'Entregando'), ('finished', 'Finalizado'), ('canceled', 'Cancelado')], default='pending', max_length=25, verbose_name='status')),
                ('payment_method', models.CharField(choices=[('credit', 'Cartão de crédito'), ('debit', 'Cartão de débito'), ('pix', 'Pix'), ('cash', 'Dinheiro')], max_length=10, verbose_name='método de pagamento')),
                ('delivery', models.BooleanField(default=False, verbose_name='entrega')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='custo de entrega')),
                ('delivery_forecast', models.DateTimeField(blank=True, default=None, null=True, verbose_name='previsão de entrega')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('products', models.ManyToManyField(blank=True, default=None, related_name='orders', to='product.product', verbose_name='produtos')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'db_table': 'order',
            },
        ),
    ]
