# Generated by Django 5.1.7 on 2025-04-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('un', 'Unidade'), ('g', 'Grama'), ('kg', 'Quilograma'), ('ml', 'Mililitro'), ('l', 'Litro')], max_length=2, verbose_name='unidade de medida'),
        ),
    ]
