# Generated by Django 5.1.7 on 2025-04-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_item_description_alter_item_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='stock',
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.IntegerField(default=0, verbose_name='tamanho'),
        ),
    ]
