# Generated by Django 5.1.7 on 2025-04-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_additionalcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcategory',
            name='additionals',
            field=models.ManyToManyField(blank=True, default=None, help_text='Adicionais a este item.', related_name='additionals', to='core.item', verbose_name='adicionais'),
        ),
    ]
