# Generated by Django 5.1.7 on 2025-04-10 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_additionalcategory_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='preço')),
                ('size', models.IntegerField(default=0, verbose_name='tamanho')),
                ('unit', models.CharField(choices=[('un', 'Unidade'), ('g', 'Grama'), ('kg', 'Quilograma'), ('ml', 'Mililitro'), ('l', 'Litro')], max_length=2, verbose_name='unidade de medida')),
                ('image', models.ImageField(upload_to='media/products/', verbose_name='imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'db_table': 'product',
            },
        ),
        migrations.AlterField(
            model_name='additionalcategory',
            name='additionals',
            field=models.ManyToManyField(blank=True, default=None, help_text='Adicionais a este item.', related_name='additional_categories', to='core.item', verbose_name='adicionais'),
        ),
        migrations.AddField(
            model_name='additionalcategory',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_categories', to='core.product', verbose_name='produto'),
        ),
    ]
