# Generated by Django 5.1.7 on 2025-04-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_alter_additionalcategory_additionals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='nome')),
                ('subtitle', models.CharField(max_length=255, verbose_name='nome')),
                ('show', models.BooleanField(default=False, verbose_name='exibir')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('products', models.ManyToManyField(blank=True, default=None, help_text='Produtos desta categoria.', related_name='product_categories', to='core.product', verbose_name='produtos')),
            ],
            options={
                'verbose_name': 'categoria do produto',
                'verbose_name_plural': 'categorias dos produtos',
                'db_table': 'product_category',
            },
        ),
    ]
