# Generated by Django 5.1.7 on 2025-04-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcategory',
            name='subtitle',
            field=models.CharField(max_length=255, verbose_name='subtítulo'),
        ),
        migrations.AlterField(
            model_name='additionalcategory',
            name='title',
            field=models.CharField(max_length=255, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='subtitle',
            field=models.CharField(max_length=255, verbose_name='subtítulo'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(max_length=255, verbose_name='título'),
        ),
    ]
