# Generated by Django 5.1.7 on 2025-04-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_additionalcategory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcategory',
            name='type',
            field=models.CharField(choices=[('choose one', 'Escolher um'), ('select multiple', 'Selecionar vários'), ('add on', 'Adicionar mais')], max_length=15, verbose_name='tipo'),
        ),
    ]
