# Generated by Django 5.1.7 on 2025-04-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_additionalcategory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/items/', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/products/', verbose_name='imagem'),
        ),
    ]
