# Generated by Django 5.1.7 on 2025-04-14 18:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_item_image_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='rua')),
                ('number', models.CharField(max_length=10, verbose_name='número')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='bairro')),
                ('city', models.CharField(max_length=255, verbose_name='cidade')),
                ('state', models.CharField(max_length=2, verbose_name='estado')),
                ('zip_code', models.CharField(blank=True, default=None, max_length=8, null=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='cep')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'endereço',
                'verbose_name_plural': 'endereços',
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='número do pedido')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('preparing', 'Preparando'), ('delivering', 'Entregando'), ('finished', 'Finalizado'), ('canceled', 'Cancelado')], default='pending', max_length=25, verbose_name='status')),
                ('payment_method', models.CharField(max_length=10, verbose_name='método de pagamento')),
                ('delivery', models.BooleanField(default=False, verbose_name='entrega')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='custo de entrega')),
                ('delivery_forecast', models.DateTimeField(blank=True, default=None, null=True, verbose_name='previsão de entrega')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('products', models.ManyToManyField(blank=True, default=None, related_name='orders', to='core.product', verbose_name='produtos')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'db_table': 'order',
            },
        ),
    ]
