# Generated by Django 5.1.7 on 2025-04-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_address_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='reference',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='ponto de referência'),
        ),
    ]
