# Generated by Django 5.1.7 on 2025-04-14 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_address_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='cep'),
        ),
    ]
