# Generated by Django 5.1.7 on 2025-04-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_address_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit', 'Cartão de crédito'), ('debit', 'Cartão de débito'), ('pix', 'Pix'), ('cash', 'Dinheiro')], max_length=10, verbose_name='método de pagamento'),
        ),
    ]
