# Generated by Django 5.1.7 on 2025-04-14 20:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='cep')),
                ('street', models.CharField(max_length=255, verbose_name='rua')),
                ('number', models.CharField(max_length=10, verbose_name='número')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='bairro')),
                ('city', models.CharField(max_length=255, verbose_name='cidade')),
                ('state', models.CharField(max_length=2, verbose_name='estado')),
                ('reference', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='ponto de referência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'endereço',
                'verbose_name_plural': 'endereços',
                'db_table': 'address',
            },
        ),
    ]
